# Generated by Django 5.2 on 2026-01-27 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('takeoff_url', models.URLField(blank=True, help_text='S3 link to takeoff document')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight per unit', max_digits=10)),
                ('is_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-shipped_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('part_identifier', models.CharField(help_text='Can differ from original part detail name', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Can differ from original price', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='projects.partdetail')),
            ],
            options={
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ShippingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight at time of shipment', max_digits=10)),
                ('part_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_parts', to='projects.partdetail')),
                ('shipping_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_parts', to='projects.shippingevent')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='partdetail',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_details', to='projects.structure'),
        ),
    ]
